{
	"patcher": {
		"fileversion": 1,
		"appversion": { "major": 8, "minor": 5, "revision": 5, "architecture": "x64", "modernui": 1 },
		"classnamespace": "box",
		"rect": [ 80.0, 80.0, 760.0, 880.0 ],
		"boxes": [
			{ "box": { "id": "obj-1", "maxclass": "inlet", "comment": "MIDI in (from midiin)", "numinlets": 0, "numoutlets": 1, "outlettype": [ "" ], "patching_rect": [ 20.0, 20.0, 30.0, 30.0 ] } },
			{ "box": { "id": "obj-2", "maxclass": "inlet", "comment": "reset (bang)", "numinlets": 0, "numoutlets": 1, "outlettype": [ "bang" ], "patching_rect": [ 120.0, 20.0, 30.0, 30.0 ] } },
			{ "box": { "id": "obj-3", "maxclass": "inlet", "comment": "fixed velocity (1-127)", "numinlets": 0, "numoutlets": 1, "outlettype": [ "" ], "patching_rect": [ 240.0, 20.0, 30.0, 30.0 ] } },
			{ "box": { "id": "obj-4", "maxclass": "outlet", "comment": "MIDI out (to midiout)", "numinlets": 1, "numoutlets": 0, "patching_rect": [ 20.0, 820.0, 30.0, 30.0 ] } },
			{ "box": { "id": "obj-25", "maxclass": "outlet", "comment": "in-pitch (last incoming note number)", "numinlets": 1, "numoutlets": 0, "patching_rect": [ 120.0, 820.0, 30.0, 30.0 ] } },
			{ "box": { "id": "obj-26", "maxclass": "outlet", "comment": "out-pitch (last mapped note number)", "numinlets": 1, "numoutlets": 0, "patching_rect": [ 220.0, 820.0, 30.0, 30.0 ] } },
			{ "box": { "id": "obj-5", "maxclass": "newobj", "text": "midiparse", "numinlets": 1, "numoutlets": 8, "outlettype": [ "", "", "", "", "", "", "", "" ], "patching_rect": [ 20.0, 70.0, 80.0, 22.0 ] } },
			{ "box": { "id": "obj-6", "maxclass": "newobj", "text": "unpack 0 0", "numinlets": 1, "numoutlets": 2, "outlettype": [ "int", "int" ], "patching_rect": [ 20.0, 120.0, 80.0, 22.0 ] } },
			{ "box": { "id": "obj-7", "maxclass": "newobj", "text": "> 0", "numinlets": 2, "numoutlets": 1, "outlettype": [ "int" ], "patching_rect": [ 130.0, 170.0, 40.0, 22.0 ] } },
			{ "box": { "id": "obj-8", "maxclass": "newobj", "text": "* 1", "numinlets": 2, "numoutlets": 1, "outlettype": [ "int" ], "patching_rect": [ 130.0, 230.0, 60.0, 22.0 ] } },
			{ "box": { "id": "obj-24", "maxclass": "newobj", "text": "pack 0 0", "numinlets": 2, "numoutlets": 1, "outlettype": [ "" ], "patching_rect": [ 20.0, 710.0, 90.0, 22.0 ] } },
			{ "box": { "id": "obj-11", "maxclass": "newobj", "text": "t i i", "numinlets": 1, "numoutlets": 2, "outlettype": [ "int", "int" ], "patching_rect": [ 20.0, 170.0, 60.0, 22.0 ] } },
			{ "box": { "id": "obj-12", "maxclass": "newobj", "text": "i", "numinlets": 2, "numoutlets": 1, "outlettype": [ "int" ], "patching_rect": [ 150.0, 360.0, 40.0, 22.0 ] } },
			{ "box": { "id": "obj-13", "maxclass": "newobj", "text": "table @size 128 @range 256", "numinlets": 2, "numoutlets": 2, "outlettype": [ "int", "bang" ], "patching_rect": [ 20.0, 420.0, 170.0, 22.0 ] } },
			{ "box": { "id": "obj-14", "maxclass": "newobj", "text": "sel 0", "numinlets": 2, "numoutlets": 2, "outlettype": [ "bang", "" ], "patching_rect": [ 20.0, 470.0, 50.0, 22.0 ] } },
			{ "box": { "id": "obj-10", "maxclass": "newobj", "text": "gate", "numinlets": 2, "numoutlets": 1, "outlettype": [ "" ], "patching_rect": [ 20.0, 520.0, 50.0, 22.0 ] } },
			{ "box": { "id": "obj-15", "maxclass": "newobj", "text": "i", "numinlets": 2, "numoutlets": 1, "outlettype": [ "int" ], "patching_rect": [ 20.0, 570.0, 40.0, 22.0 ] } },
			{ "box": { "id": "obj-17", "maxclass": "newobj", "text": "t b i i i", "numinlets": 1, "numoutlets": 4, "outlettype": [ "bang", "int", "int", "int" ], "patching_rect": [ 20.0, 620.0, 100.0, 22.0 ] } },
			{ "box": { "id": "obj-16", "maxclass": "newobj", "text": "+ 1", "numinlets": 2, "numoutlets": 1, "outlettype": [ "int" ], "patching_rect": [ 250.0, 660.0, 40.0, 22.0 ] } },
			{ "box": { "id": "obj-18", "maxclass": "newobj", "text": "pack 0 0", "numinlets": 2, "numoutlets": 1, "outlettype": [ "" ], "patching_rect": [ 130.0, 680.0, 70.0, 22.0 ] } },
			{ "box": { "id": "obj-19", "maxclass": "newobj", "text": "midiformat", "numinlets": 8, "numoutlets": 1, "outlettype": [ "int" ], "patching_rect": [ 20.0, 760.0, 90.0, 22.0 ] } },
			{ "box": { "id": "obj-20", "maxclass": "newobj", "text": "loadbang", "numinlets": 1, "numoutlets": 1, "outlettype": [ "bang" ], "patching_rect": [ 460.0, 20.0, 70.0, 22.0 ] } },
			{ "box": { "id": "obj-21", "maxclass": "newobj", "text": "t b b", "numinlets": 1, "numoutlets": 2, "outlettype": [ "bang", "bang" ], "patching_rect": [ 460.0, 70.0, 50.0, 22.0 ] } },
			{ "box": { "id": "obj-22", "maxclass": "message", "text": "clear", "numinlets": 2, "numoutlets": 1, "outlettype": [ "" ], "patching_rect": [ 460.0, 120.0, 50.0, 22.0 ] } },
			{ "box": { "id": "obj-23", "maxclass": "message", "text": "36", "numinlets": 2, "numoutlets": 1, "outlettype": [ "" ], "patching_rect": [ 540.0, 120.0, 50.0, 22.0 ] } },
			{ "box": { "id": "obj-comment-1", "maxclass": "comment", "text": "notemap: first-seen input note -> next chromatic output starting C1 (36). Map is sticky until reset.", "numinlets": 1, "numoutlets": 0, "patching_rect": [ 220.0, 470.0, 360.0, 40.0 ] } }
		],
		"lines": [
			{ "patchline": { "source": [ "obj-1", 0 ], "destination": [ "obj-5", 0 ] } },
			{ "patchline": { "source": [ "obj-5", 0 ], "destination": [ "obj-6", 0 ] } },
			{ "patchline": { "source": [ "obj-6", 1 ], "destination": [ "obj-7", 0 ] } },
			{ "patchline": { "source": [ "obj-6", 0 ], "destination": [ "obj-11", 0 ] } },
			{ "patchline": { "source": [ "obj-7", 0 ], "destination": [ "obj-8", 0 ] } },
			{ "patchline": { "source": [ "obj-7", 0 ], "destination": [ "obj-10", 0 ] } },
			{ "patchline": { "source": [ "obj-3", 0 ], "destination": [ "obj-8", 1 ] } },
			{ "patchline": { "source": [ "obj-8", 0 ], "destination": [ "obj-24", 1 ] } },
			{ "patchline": { "source": [ "obj-11", 1 ], "destination": [ "obj-12", 1 ] } },
			{ "patchline": { "source": [ "obj-11", 0 ], "destination": [ "obj-13", 0 ] } },
			{ "patchline": { "source": [ "obj-13", 0 ], "destination": [ "obj-14", 0 ] } },
			{ "patchline": { "source": [ "obj-14", 0 ], "destination": [ "obj-10", 1 ] } },
			{ "patchline": { "source": [ "obj-14", 1 ], "destination": [ "obj-24", 0 ] } },
			{ "patchline": { "source": [ "obj-10", 0 ], "destination": [ "obj-15", 0 ] } },
			{ "patchline": { "source": [ "obj-15", 0 ], "destination": [ "obj-17", 0 ] } },
			{ "patchline": { "source": [ "obj-17", 3 ], "destination": [ "obj-16", 0 ] } },
			{ "patchline": { "source": [ "obj-17", 2 ], "destination": [ "obj-18", 1 ] } },
			{ "patchline": { "source": [ "obj-17", 1 ], "destination": [ "obj-24", 0 ] } },
			{ "patchline": { "source": [ "obj-24", 0 ], "destination": [ "obj-19", 0 ] } },
			{ "patchline": { "source": [ "obj-17", 0 ], "destination": [ "obj-12", 0 ] } },
			{ "patchline": { "source": [ "obj-16", 0 ], "destination": [ "obj-15", 1 ] } },
			{ "patchline": { "source": [ "obj-12", 0 ], "destination": [ "obj-18", 0 ] } },
			{ "patchline": { "source": [ "obj-18", 0 ], "destination": [ "obj-13", 0 ] } },
			{ "patchline": { "source": [ "obj-19", 0 ], "destination": [ "obj-4", 0 ] } },
			{ "patchline": { "source": [ "obj-20", 0 ], "destination": [ "obj-21", 0 ] } },
			{ "patchline": { "source": [ "obj-2", 0 ], "destination": [ "obj-21", 0 ] } },
			{ "patchline": { "source": [ "obj-21", 0 ], "destination": [ "obj-23", 0 ] } },
			{ "patchline": { "source": [ "obj-21", 1 ], "destination": [ "obj-22", 0 ] } },
			{ "patchline": { "source": [ "obj-23", 0 ], "destination": [ "obj-15", 1 ] } },
			{ "patchline": { "source": [ "obj-22", 0 ], "destination": [ "obj-13", 0 ] } },
			{ "patchline": { "source": [ "obj-6", 0 ], "destination": [ "obj-25", 0 ] } },
			{ "patchline": { "source": [ "obj-14", 1 ], "destination": [ "obj-26", 0 ] } },
			{ "patchline": { "source": [ "obj-17", 1 ], "destination": [ "obj-26", 0 ] } }
		]
	}
}
